// GENERATED FILE - do not edit by hand.
// Source: the Canary Cove photo manifest (site registry + Cloudinary ingests).
// Regenerate with the manifest pipeline when new photos are added; the page and
// its filters are fully data-driven, so a new photo drop is a pure data change.

export type GalleryCategory =
  | "suites-bedrooms"
  | "living-spaces"
  | "pool"
  | "villa-exterior"
  | "beach-dock"
  | "dining-food"
  | "staff-people"
  | "experiences-water"
  | "experiences-land"
  | "sunset-views"
  | "celebrations"
  | "other"

export type GallerySource = "site" | "gil-2026-07" | "album-2021"

export type GallerySuite = "suite-1" | "suite-2" | "suite-3" | "bunk-room"

export type GalleryAmenity = "pool" | "infinity-edge" | "pool-bar" | "hot-tub"

export type GalleryPhoto = {
  id: string
  src: string
  alt: string
  category: GalleryCategory
  tags: string[]
  width: number
  height: number
  source: GallerySource
  /** Site pages/components this photo already appears on. Empty for archive photos. */
  usedIn: string[]
  /** Suite assignment for suites-bedrooms photos. Undefined until confirmed by Don/Gil. */
  suite?: GallerySuite
  /**
   * Amenity sub-groups for pool photos. Every assignment is backed by the
   * photo's own caption/tags — nothing here is inferred from what a pool
   * "probably" is. A photo can belong to several sub-groups (an infinity pool
   * with a swim-up bar is both).
   */
  amenities?: GalleryAmenity[]
}

export const GALLERY_CATEGORIES: { id: GalleryCategory; label: string }[] = [
  { id: "suites-bedrooms", label: "Suites & bedrooms" },
  { id: "pool", label: "Pool & terrace" },
  { id: "living-spaces", label: "Living spaces" },
  { id: "villa-exterior", label: "Grounds & exterior" },
  { id: "beach-dock", label: "Beach & dock" },
  { id: "dining-food", label: "Dining & food" },
  { id: "staff-people", label: "Team & people" },
  { id: "experiences-water", label: "On the water" },
  { id: "experiences-land", label: "Island & mainland" },
  { id: "sunset-views", label: "Sunsets & views" },
  { id: "celebrations", label: "Celebrations" },
  { id: "other", label: "More moments" },
]

export const GALLERY_PHOTOS: GalleryPhoto[] = [
  {
    id: "bathroomAlt",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059660/canarycove-haydeelustudio-10-scaled_bp10wc.webp",
    alt: "Contemporary villa bathroom",
    category: "suites-bedrooms",
    tags: ["bathroom", "en-suite", "contemporary"],
    width: 2880,
    height: 1922,
    source: "site",
    usedIn: ["app/page.tsx", "components/stay-villa-gallery.tsx"],
  },
  {
    id: "livingRoom",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059675/canarycove-haydeelustudio-32-scaled_forayc.webp",
    alt: "Villa living room with airy seating and harbor views",
    category: "living-spaces",
    tags: ["living room", "seating", "harbor view"],
    width: 2880,
    height: 1923,
    source: "site",
    usedIn: ["components/stay-villa-gallery.tsx", "lib/homepage-content.ts", "lib/site-config.ts"],
  },
  {
    id: "heroBackgroundPool",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059679/Screen-Shot-2021-02-02-at-12.26.22-PM_f7hcp3.webp",
    alt: "Infinity pool with yellow umbrellas beside the villa",
    category: "pool",
    tags: ["infinity pool", "umbrellas", "sun loungers"],
    width: 1496,
    height: 974,
    source: "site",
    usedIn: [],
    amenities: ["infinity-edge"],
  },
  {
    id: "bikes",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059644/IMG_1833_sapr8q.webp",
    alt: "Bikes ready for guests at Canary Cove",
    category: "villa-exterior",
    tags: ["bikes", "amenities", "grounds"],
    width: 5184,
    height: 3456,
    source: "site",
    usedIn: ["components/stay-outdoor-gallery.tsx"],
  },
  {
    id: "mainDock",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059660/Dive-Shop-Facilities_800x532_p2fr9k.webp",
    alt: "Main dock with boats ready for departure",
    category: "beach-dock",
    tags: ["dock", "boats", "departure"],
    width: 800,
    height: 532,
    source: "site",
    usedIn: ["app/experiences/page.tsx", "components/experiences-mini-gallery.tsx", "components/stay-highlights.tsx", "components/stay-mini-gallery.tsx", "components/stay-outdoor-gallery.tsx", "lib/homepage-content.ts", "lib/site-config.ts", "lib/structured-data.ts"],
  },
  {
    id: "caramba",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059664/Caramba-1-768x768_ezqnes.webp",
    alt: "Caramba dining experience",
    category: "dining-food",
    tags: ["Caramba", "dining out", "san pedro", "restaurant"],
    width: 768,
    height: 768,
    source: "site",
    usedIn: ["app/dining/page.tsx"],
  },
  {
    id: "gilBoat",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059658/fullsizeoutput_56c2_v4e6kt.webp",
    alt: "Gil at the front of the boat",
    category: "staff-people",
    tags: ["Gil", "boat", "host"],
    width: 5184,
    height: 3456,
    source: "site",
    usedIn: ["components/stay-guest-experience.tsx"],
  },
  {
    id: "adventureGroup",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059631/IMG_1127_ytzxff.webp",
    alt: "Guests enjoying an island outing on the water",
    category: "experiences-water",
    tags: ["island outing", "guests", "boat"],
    width: 5472,
    height: 3648,
    source: "site",
    usedIn: ["app/experiences/page.tsx"],
  },
  {
    id: "belizeSign",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059643/I-Love-Belize_xtimfq.webp",
    alt: "Guests posing beside the I Love Belize sign",
    category: "experiences-land",
    tags: ["I Love Belize sign", "photo stop", "san pedro"],
    width: 2048,
    height: 1536,
    source: "site",
    usedIn: ["app/experiences/page.tsx"],
  },
  {
    id: "romanticViews",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059674/relax_drhybs.webp",
    alt: "Couple relaxing by the water with sunset views",
    category: "sunset-views",
    tags: ["couple", "sunset", "waterfront", "romantic"],
    width: 800,
    height: 540,
    source: "site",
    usedIn: ["app/dining/page.tsx", "app/page.tsx", "components/experiences-mini-gallery.tsx", "components/stay-guest-experience.tsx", "lib/homepage-content.ts", "lib/seo.ts", "lib/site-config.ts"],
  },
  {
    id: "wedding",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059678/IMG_7109_qmc7yh.webp",
    alt: "Wedding couple celebrating at Canary Cove",
    category: "celebrations",
    tags: ["wedding", "celebration", "couple", "event"],
    width: 1920,
    height: 1280,
    source: "site",
    usedIn: ["components/photo-carousel.tsx"],
  },
  {
    id: "canarycove-album2021-007",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546990/canarycove-album2021-007.jpg",
    alt: "Coastal powder room with louvered details and ocean glimpses through a porthole window.",
    category: "other",
    tags: ["powder-room", "ocean-view", "tropical-style", "luxury"],
    width: 2400,
    height: 3200,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "bedDetail",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059640/Towel-Attention-to-Detail-2_m0jfj3.webp",
    alt: "Bed details with folded towels",
    category: "suites-bedrooms",
    tags: ["bed", "towels", "turndown", "detail"],
    width: 1500,
    height: 1000,
    source: "site",
    usedIn: ["components/stay-villa-gallery.tsx"],
  },
  {
    id: "livingRoomAlt",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059650/40_villa_cropped_tdazsh.webp",
    alt: "Great room with lounge, kitchen, and dining area",
    category: "living-spaces",
    tags: ["great room", "lounge", "kitchen", "dining area"],
    width: 800,
    height: 500,
    source: "site",
    usedIn: [],
  },
  {
    id: "heroVillaDetail",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1767202746/canarycove-haydeelustudio-56_1_dhk9k9.webp",
    alt: "Infinity pool and swim-up bar with villa view",
    category: "pool",
    tags: ["infinity pool", "swim-up bar", "villa view"],
    width: 3600,
    height: 2403,
    source: "site",
    usedIn: ["components/stay-highlights.tsx", "components/stay-outdoor-gallery.tsx"],
    amenities: ["infinity-edge", "pool-bar"],
  },
  {
    id: "hammock",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059676/Facilities-Shot_dyshzq.webp",
    alt: "Hammock and palms by the water",
    category: "villa-exterior",
    tags: ["hammock", "palms", "waterfront", "relaxing"],
    width: 1500,
    height: 1000,
    source: "site",
    usedIn: ["app/experiences/page.tsx", "components/stay-outdoor-gallery.tsx"],
  },
  {
    id: "canarycove-album2021-074",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547006/canarycove-album2021-074.jpg",
    alt: "Beachfront thatch-roof cabana nestled among palms and tropical vegetation.",
    category: "beach-dock",
    tags: ["beach cabana", "thatch roof", "palm trees", "sandy beach"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "chipsAndDrinks",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059670/IMG_1897_nu4gs3.webp",
    alt: "Chips and drinks served with Canary Cove branding",
    category: "dining-food",
    tags: ["snacks", "drinks", "branding"],
    width: 5184,
    height: 3456,
    source: "site",
    usedIn: ["app/dining/page.tsx"],
  },
  {
    id: "canarycove-gil2026-18e6107c",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546985/canarycove-gil2026-18e6107c.jpg",
    alt: "Executive chef presents seared meat entrées in the villa's professional kitchen",
    category: "staff-people",
    tags: ["chef", "kitchen", "cuisine", "culinary", "marvin", "chef marvin"],
    width: 960,
    height: 1280,
    source: "gil-2026-07",
    usedIn: [],
  },
  {
    id: "divingFun",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059679/20160127_Belize_017_scubaHangloose_800x532_djqpmm.webp",
    alt: "Diver underwater surrounded by clear blue water",
    category: "experiences-water",
    tags: ["diving", "scuba", "underwater", "reef"],
    width: 800,
    height: 532,
    source: "site",
    usedIn: ["app/adventures/page.tsx", "components/experiences-mini-gallery.tsx", "lib/seo.ts", "lib/site-config.ts"],
  },
  {
    id: "caveTubing",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059671/Cave-Tubing_kapbq1.webp",
    alt: "Guests floating through a cave on an inner tube",
    category: "experiences-land",
    tags: ["cave tubing", "excursion", "mainland"],
    width: 1024,
    height: 768,
    source: "site",
    usedIn: ["components/experiences-mini-gallery.tsx"],
  },
  {
    id: "canarycove-album2021-078",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547007/canarycove-album2021-078.jpg",
    alt: "Sunset-lit oceanfront terrace with lounge seating, pool, and golden-hour lighting.",
    category: "sunset-views",
    tags: ["sunset view", "oceanfront patio", "golden light", "evening glow"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "bedroomGardenView",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059615/canarycove-haydeelustudio-4-scaled_vcivyg.webp",
    alt: "Bedroom with garden view",
    category: "suites-bedrooms",
    tags: ["bedroom", "garden view", "suite"],
    width: 2880,
    height: 1922,
    source: "site",
    usedIn: ["components/stay-highlights.tsx", "components/stay-villa-gallery.tsx"],
  },
  {
    id: "livingRoomPhoto",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059648/canarycove-haydeelustudio-34-scaled_hemax4.webp",
    alt: "Main lounge with water-facing windows",
    category: "living-spaces",
    tags: ["lounge", "windows", "water view"],
    width: 2880,
    height: 1923,
    source: "site",
    usedIn: [],
  },
  {
    id: "heroVillaDining",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1767202756/canarycove-haydeelustudio-55_gimbjx.webp",
    alt: "Pool terrace beside the villa exterior",
    category: "pool",
    tags: ["pool terrace", "villa exterior"],
    width: 7200,
    height: 4806,
    source: "site",
    usedIn: [],
    amenities: ["pool"],
  },
  {
    id: "helipad",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059658/imgp0667_z0hk3t.webp",
    alt: "Helipad near the shoreline at Canary Cove",
    category: "villa-exterior",
    tags: ["helipad", "arrival", "shoreline"],
    width: 800,
    height: 600,
    source: "site",
    usedIn: ["app/getting-here/page.tsx", "lib/site-config.ts"],
  },
  {
    id: "canarycove-album2021-079",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547007/canarycove-album2021-079.jpg",
    alt: "Rustic beachfront thatched shelter with palm fronds and tropical island atmosphere.",
    category: "beach-dock",
    tags: ["beach structure", "thatched roof", "tropical shelter", "sandy ground"],
    width: 2400,
    height: 1603,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "diningDetailThree",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059627/IMG_3839-1-e1506956062818_worenb.webp",
    alt: "Plated dinner presentation prepared for guests",
    category: "dining-food",
    tags: ["plated dinner", "presentation"],
    width: 1334,
    height: 750,
    source: "site",
    usedIn: ["app/dining/page.tsx"],
  },
  {
    id: "canarycove-gil2026-6e7e9791",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546986/canarycove-gil2026-6e7e9791.jpg",
    alt: "Master mixologist showcasing signature tropical cocktails in an elegantly appointed kitchen",
    category: "staff-people",
    tags: ["mixologist", "cocktails", "bartender", "service", "marvin", "chef marvin"],
    width: 960,
    height: 1280,
    source: "gil-2026-07",
    usedIn: [],
  },
  {
    id: "fishingTrophy",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059667/AndrewWithTrophy_r1ubw6.webp",
    alt: "Guest holding a trophy catch",
    category: "experiences-water",
    tags: ["fishing", "catch", "trophy"],
    width: 640,
    height: 360,
    source: "site",
    usedIn: ["lib/site-config.ts"],
  },
  {
    id: "jungleAdventure",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059628/IMG_2121_jntwjo.webp",
    alt: "Guests on a Belize jungle excursion",
    category: "experiences-land",
    tags: ["jungle", "excursion", "mainland"],
    width: 5184,
    height: 3456,
    source: "site",
    usedIn: [],
  },
  {
    id: "villaBedroom",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059668/canarycove-haydeelustudio-12-1280x854_r5xlpw.webp",
    alt: "Villa bedroom with pool view and natural light",
    category: "suites-bedrooms",
    tags: ["bedroom", "pool view", "natural light", "suite"],
    width: 1280,
    height: 854,
    source: "site",
    usedIn: ["components/stay-highlights.tsx", "components/stay-villa-gallery.tsx", "lib/homepage-content.ts", "lib/site-config.ts"],
  },
  {
    id: "viewFromKitchen",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059649/canarycove-haydeelustudio-44-scaled_pmxxyx.webp",
    alt: "Kitchen island facing the great room",
    category: "living-spaces",
    tags: ["kitchen", "island", "great room"],
    width: 2880,
    height: 1922,
    source: "site",
    usedIn: ["app/dining/page.tsx", "components/stay-villa-gallery.tsx"],
  },
  {
    id: "heroVillaInterior",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1767202746/canarycove-haydeelustudio-54_1_cvfho6.webp",
    alt: "Pool terrace looking toward the water",
    category: "pool",
    tags: ["pool terrace", "water view"],
    width: 3600,
    height: 2403,
    source: "site",
    usedIn: [],
    amenities: ["pool"],
  },
  {
    id: "heroBackgroundEstate",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059680/IMG_1835_w1onmi.webp",
    alt: "Beach path view of the pink Canary Cove villa and pool terrace",
    category: "villa-exterior",
    tags: ["villa", "beach path", "exterior", "pool terrace"],
    width: 5184,
    height: 3456,
    source: "site",
    usedIn: ["app/rates/page.tsx", "components/experiences-hero.tsx"],
  },
  {
    id: "diningDetailTwo",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059642/IMG_3832-1_z37xde.webp",
    alt: "Chef-prepared dining detail served at Canary Cove",
    category: "dining-food",
    tags: ["plated dish", "chef-prepared"],
    width: 1334,
    height: 750,
    source: "site",
    usedIn: ["app/dining/page.tsx"],
  },
  {
    id: "canarycove-gil2026-95cc7152",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546987/canarycove-gil2026-95cc7152.jpg",
    alt: "Chef presents perfectly grilled meat dish in a modern kitchen with designer lighting",
    category: "staff-people",
    tags: ["chef", "grilled-meat", "kitchen", "plating", "marvin", "chef marvin"],
    width: 960,
    height: 1280,
    source: "gil-2026-07",
    usedIn: [],
  },
  {
    id: "guestSnorkelGroup",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059678/IMG_8895_Guests_SCUBA_and_Snorkel_gallery-1-400x284_w6uizz.webp",
    alt: "Guests floating together during a snorkeling stop in clear water",
    category: "experiences-water",
    tags: ["snorkeling", "guests", "group", "clear water"],
    width: 400,
    height: 284,
    source: "site",
    usedIn: ["app/adventures/page.tsx"],
  },
  {
    id: "landAdventure",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059646/land_qmx9ht.webp",
    alt: "Guests on a mainland Belize adventure excursion",
    category: "experiences-land",
    tags: ["mainland", "excursion", "adventure"],
    width: 800,
    height: 540,
    source: "site",
    usedIn: ["app/adventures/page.tsx", "components/experiences-mini-gallery.tsx"],
  },
  {
    id: "villaMasterBedroom",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059661/canarycove-haydeelustudio-22-scaled_j6fxkl.webp",
    alt: "Villa master bedroom with airy views",
    category: "suites-bedrooms",
    tags: ["master bedroom", "suite", "views"],
    width: 2880,
    height: 1922,
    source: "site",
    usedIn: ["components/stay-guest-experience.tsx", "components/stay-highlights.tsx", "components/stay-mini-gallery.tsx", "components/stay-villa-gallery.tsx"],
  },
  {
    id: "villaInteriorWide",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059618/canarycove-haydeelustudio-36-scaled_y92qno.webp",
    alt: "Wide view of the great room with kitchen and dining area",
    category: "living-spaces",
    tags: ["great room", "kitchen", "dining area", "open plan"],
    width: 2880,
    height: 1922,
    source: "site",
    usedIn: ["components/stay-closing-cta.tsx", "components/stay-highlights.tsx", "components/stay-mini-gallery.tsx", "components/stay-villa-gallery.tsx", "lib/homepage-content.ts"],
  },
  {
    id: "heroVillaLiving",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1767202751/canarycove-haydeelustudio-56_ixnmn0.webp",
    alt: "Swim-up bar on the infinity pool",
    category: "pool",
    tags: ["swim-up bar", "infinity pool"],
    width: 7200,
    height: 4806,
    source: "site",
    usedIn: [],
    amenities: ["infinity-edge", "pool-bar"],
  },
  {
    id: "heroBackgroundLawn",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1767202762/canarycove-haydeelustudio-48_wciu3z.webp",
    alt: "Wide lawn view of the villa, pool, and terrace",
    category: "villa-exterior",
    tags: ["lawn", "pool", "terrace", "villa"],
    width: 7200,
    height: 4807,
    source: "site",
    usedIn: [],
  },
  {
    id: "diningFoodDetail",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059673/Food-detail_gallery_by2pcb.webp",
    alt: "Close-up of a chef-prepared dish at Canary Cove",
    category: "dining-food",
    tags: ["plated dish", "chef-prepared", "close-up"],
    width: 1000,
    height: 667,
    source: "site",
    usedIn: ["app/dining/page.tsx", "components/stay-highlights.tsx"],
  },
  {
    id: "canarycove-gil2026-b6466160",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546987/canarycove-gil2026-b6466160.jpg",
    alt: "Chef displays fresh fruit and produce platters in the villa's culinary hallway",
    category: "staff-people",
    tags: ["chef", "service", "kitchen", "culinary-team", "marvin", "chef marvin"],
    width: 960,
    height: 1280,
    source: "gil-2026-07",
    usedIn: [],
  },
  {
    id: "kidsPlatform",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059668/Platform-Kids-Activities_800x532-400x284_rpctnj.webp",
    alt: "Guests relaxing from the floating snorkel platform with yellow umbrellas overhead",
    category: "experiences-water",
    tags: ["snorkel platform", "floating", "umbrellas", "family"],
    width: 400,
    height: 284,
    source: "site",
    usedIn: ["app/adventures/page.tsx"],
  },
  {
    id: "mainlandJaguar",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059675/IMG_57061_zbipzu.webp",
    alt: "Jaguar resting during a mainland Belize wildlife excursion",
    category: "experiences-land",
    tags: ["jaguar", "wildlife", "zoo", "mainland"],
    width: 1536,
    height: 2048,
    source: "site",
    usedIn: ["app/adventures/page.tsx"],
  },
  {
    id: "canarycove-album2021-001",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546989/canarycove-album2021-001.jpg",
    alt: "Spa-inspired en-suite bathroom with dual vanities, blue subway tile accents, and luxe finishes.",
    category: "suites-bedrooms",
    tags: ["bathroom", "en-suite", "dual-vanity", "tile-work"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-002",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546989/canarycove-album2021-002.jpg",
    alt: "Expansive great room with sculptural ceiling fans, relaxed furnishings, and seamless indoor-outdoor flow.",
    category: "living-spaces",
    tags: ["lounge", "great-room", "ocean-view", "contemporary"],
    width: 2400,
    height: 1603,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "heroVillaSeating",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1767202762/canarycove-haydeelustudio-59_x8gmzo.webp",
    alt: "Pool deck with shaded loungers beside the villa",
    category: "pool",
    tags: ["pool deck", "loungers", "shade", "umbrellas"],
    width: 7200,
    height: 4806,
    source: "site",
    usedIn: ["app/layout.tsx", "components/stay-closing-cta.tsx", "components/stay-highlights.tsx", "components/stay-mini-gallery.tsx", "components/stay-outdoor-gallery.tsx", "lib/homepage-content.ts", "lib/seo.ts", "lib/site-config.ts", "lib/structured-data.ts"],
    amenities: ["pool"],
  },
  {
    id: "villaLawn",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059671/VillaFromLawn_800x538-768x516_akhcfd.webp",
    alt: "Villa exterior view from the lawn",
    category: "villa-exterior",
    tags: ["lawn", "villa", "exterior"],
    width: 768,
    height: 516,
    source: "site",
    usedIn: ["components/stay-closing-cta.tsx", "components/stay-outdoor-gallery.tsx", "lib/seo.ts", "lib/site-config.ts"],
  },
  {
    id: "diningPlatter",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059673/IMG_3845-1_ybzoab.webp",
    alt: "Chef-prepared platter at Canary Cove",
    category: "dining-food",
    tags: ["platter", "chef-prepared", "sharing"],
    width: 750,
    height: 1334,
    source: "site",
    usedIn: ["app/dining/page.tsx"],
  },
  {
    id: "canarycove-gil2026-cfb8d7ac",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546987/canarycove-gil2026-cfb8d7ac.jpg",
    alt: "Chef proudly presents grilled entrée and vegetable accompaniments in the contemporary kitchen",
    category: "staff-people",
    tags: ["chef", "plating", "grilled", "service", "marvin", "chef marvin"],
    width: 960,
    height: 1280,
    source: "gil-2026-07",
    usedIn: [],
  },
  {
    id: "lionFishCatch",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059647/Don-Gill-Lion-Fish_800x532-768x511_ziyqmz.webp",
    alt: "Lionfish catch on the boat",
    category: "experiences-water",
    tags: ["lionfish", "fishing", "boat"],
    width: 768,
    height: 511,
    source: "site",
    usedIn: [],
  },
  {
    id: "sanPedroSouvenirs",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059623/SanPedroSouvenirs-400x284_qlefym.webp",
    alt: "Souvenir shopping scene in San Pedro Town",
    category: "experiences-land",
    tags: ["shopping", "souvenirs", "san pedro", "town"],
    width: 400,
    height: 284,
    source: "site",
    usedIn: ["app/adventures/page.tsx"],
  },
  {
    id: "canarycove-album2021-003",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546989/canarycove-album2021-003.jpg",
    alt: "Serene master bedroom with botanical bedding, private veranda, and unobstructed Caribbean views.",
    category: "suites-bedrooms",
    tags: ["master-suite", "ocean-view", "beachfront", "ensuite"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-014",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546992/canarycove-album2021-014.jpg",
    alt: "Sophisticated suite living area with panoramic ocean views, designer furnishings, and resort-style patio.",
    category: "living-spaces",
    tags: ["suite-lounge", "ocean-view", "veranda", "luxury-seating"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "hotTub",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059665/IMG_3051-1-980x735_amac1q.webp",
    alt: "Hot tub with view of the bay",
    category: "pool",
    tags: ["hot tub", "bay view", "outdoor amenity"],
    width: 980,
    height: 735,
    source: "site",
    usedIn: ["components/stay-highlights.tsx", "components/stay-outdoor-gallery.tsx"],
    amenities: ["hot-tub"],
  },
  {
    id: "villaSign",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059672/31_villa_sign_beach_path_entry_lwypad.webp",
    alt: "Canary Cove sign along beach path entry",
    category: "villa-exterior",
    tags: ["sign", "entry", "beach path"],
    width: 800,
    height: 532,
    source: "site",
    usedIn: [],
  },
  {
    id: "diningRoom",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059653/canarycove-haydeelustudio-37-scaled_y1yw74.webp",
    alt: "Villa dining room prepared for dinner",
    category: "dining-food",
    tags: ["dining room", "table setting", "dinner"],
    width: 2880,
    height: 1922,
    source: "site",
    usedIn: ["app/dining/page.tsx", "app/rates/page.tsx", "components/stay-highlights.tsx", "components/stay-villa-gallery.tsx", "lib/homepage-content.ts", "lib/site-config.ts"],
  },
  {
    id: "canarycove-gil2026-e17dd476",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546987/canarycove-gil2026-e17dd476.jpg",
    alt: "Culinary artistry on display: grilled protein with vibrant vegetable medley and garnish",
    category: "staff-people",
    tags: ["chef", "plating", "grilled", "contemporary", "marvin", "chef marvin"],
    width: 960,
    height: 1280,
    source: "gil-2026-07",
    usedIn: [],
  },
  {
    id: "scubaPhoto",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059659/2B8A8650_hydrusDivers_fjym7k.webp",
    alt: "Diver photographing marine life",
    category: "experiences-water",
    tags: ["scuba", "photography", "marine life"],
    width: 5760,
    height: 3840,
    source: "site",
    usedIn: ["app/adventures/page.tsx", "lib/seo.ts", "lib/site-config.ts"],
  },
  {
    id: "sanPedroWelcome",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059658/SanPedroWelcome_zhaw9p.webp",
    alt: "San Pedro welcome sign",
    category: "experiences-land",
    tags: ["san pedro", "town", "sign"],
    width: 1920,
    height: 1080,
    source: "site",
    usedIn: ["app/getting-here/page.tsx", "lib/seo.ts", "lib/site-config.ts"],
  },
  {
    id: "canarycove-album2021-004",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546989/canarycove-album2021-004.jpg",
    alt: "Luxury dual-sink vanity bathroom with extensive storage and designer tile detailing.",
    category: "suites-bedrooms",
    tags: ["bathroom", "vanity", "tile-design", "spacious"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-017",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546993/canarycove-album2021-017.jpg",
    alt: "Grand oceanfront master lounge with woven furnishings, sculptural ceiling fans, and palm-canopy views.",
    category: "living-spaces",
    tags: ["master-lounge", "oceanfront", "tropical-design", "veranda"],
    width: 2400,
    height: 1603,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "villaPool",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059677/outside_sq8dvn.webp",
    alt: "Villa pool and deck overlooking the water",
    category: "pool",
    tags: ["pool", "deck", "waterfront"],
    width: 1920,
    height: 1080,
    source: "site",
    usedIn: ["app/rates/page.tsx", "components/photo-carousel.tsx", "components/stay-highlights.tsx", "components/stay-mini-gallery.tsx", "components/stay-outdoor-gallery.tsx", "lib/homepage-content.ts", "lib/seo.ts", "lib/site-config.ts", "lib/structured-data.ts"],
    amenities: ["pool"],
  },
  {
    id: "canarycove-album2021-046",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547000/canarycove-album2021-046.jpg",
    alt: "Charming villa pathways lined with tropical plantings and traditional thatched-roof cottages.",
    category: "villa-exterior",
    tags: ["bungalows", "thatched roof", "tropical plants", "pathways"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "diningSpread",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059648/fullsizeoutput_56b3_ijpj4e.webp",
    alt: "Dining spread prepared by the chef",
    category: "dining-food",
    tags: ["spread", "chef-prepared", "buffet"],
    width: 5184,
    height: 3456,
    source: "site",
    usedIn: ["app/dining/page.tsx", "components/stay-highlights.tsx"],
  },
  {
    id: "canarycove-gil2026-eb3ab337",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546988/canarycove-gil2026-eb3ab337.jpg",
    alt: "Chef expertly flame-sears premium meat at the kitchen wok, creating a theatrical culinary moment",
    category: "staff-people",
    tags: ["chef", "wok-cooking", "flame", "skill", "marvin", "chef marvin"],
    width: 960,
    height: 1280,
    source: "gil-2026-07",
    usedIn: [],
  },
  {
    id: "tubing",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059664/kids_tubing_nlrbc1.webp",
    alt: "Kids tubing behind a boat on clear water",
    category: "experiences-water",
    tags: ["tubing", "boat", "kids", "family"],
    width: 1920,
    height: 1080,
    source: "site",
    usedIn: ["components/experiences-mini-gallery.tsx", "components/photo-carousel.tsx", "lib/homepage-content.ts"],
  },
  {
    id: "zooVisit",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059646/IMG_7247_vrmxgl.webp",
    alt: "Guests exploring a Belize zoo day trip",
    category: "experiences-land",
    tags: ["zoo", "day trip", "wildlife"],
    width: 5184,
    height: 3456,
    source: "site",
    usedIn: ["app/experiences/page.tsx"],
  },
  {
    id: "canarycove-album2021-005",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546990/canarycove-album2021-005.jpg",
    alt: "Bright guest bedroom with botanical linens and natural light from oversized windows.",
    category: "suites-bedrooms",
    tags: ["guest-room", "bedroom", "comfortable", "natural-light"],
    width: 2400,
    height: 3200,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-032",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546996/canarycove-album2021-032.jpg",
    alt: "Contemporary chef's kitchen with island, stainless steel appliances, and panoramic views.",
    category: "living-spaces",
    tags: ["kitchen", "chef's kitchen", "modern appliances", "ocean view"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-008",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546991/canarycove-album2021-008.png",
    alt: "Infinity pool with sculptured crocodile sculpture overlooking crystalline Caribbean waters.",
    category: "pool",
    tags: ["infinity-pool", "oceanfront", "sun-loungers", "tropical"],
    width: 1496,
    height: 932,
    source: "album-2021",
    usedIn: [],
    amenities: ["infinity-edge"],
  },
  {
    id: "canarycove-album2021-057",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547003/canarycove-album2021-057.jpg",
    alt: "Pink villa facade with sweeping curved steps and vibrant umbrellas overlooking manicured lawns.",
    category: "villa-exterior",
    tags: ["pink architecture", "main building", "entrance stairs", "tropical setting"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "diningTable",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059655/f9564a98-afc6-48db-905e-bb539e521a84_xtz7v1.webp",
    alt: "Dining table setting",
    category: "dining-food",
    tags: ["table setting", "dinner", "place setting"],
    width: 960,
    height: 1280,
    source: "site",
    usedIn: ["app/dining/page.tsx"],
  },
  {
    id: "canarycove-gil2026-f07c60e2",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546988/canarycove-gil2026-f07c60e2.jpg",
    alt: "Chef serves an artfully plated grilled dish with seasonal vegetables in the villa's kitchen",
    category: "staff-people",
    tags: ["chef", "plating", "service", "contemporary", "marvin", "chef marvin"],
    width: 960,
    height: 1280,
    source: "gil-2026-07",
    usedIn: [],
  },
  {
    id: "turtleDive",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059665/Don-LIstwin-Turtles-Fish_800x532-768x511_zwoetm.webp",
    alt: "Sea turtle swimming alongside divers",
    category: "experiences-water",
    tags: ["sea turtle", "wildlife", "diving", "snorkeling"],
    width: 768,
    height: 511,
    source: "site",
    usedIn: ["app/experiences/page.tsx", "components/photo-carousel.tsx"],
  },
  {
    id: "canarycove-gil2026-90b2df07",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546986/canarycove-gil2026-90b2df07.jpg",
    alt: "Open-fire cooking under swaying palms exemplifies the villa's authentic culinary experience",
    category: "experiences-land",
    tags: ["outdoor-cooking", "fire-pit", "culinary-experience", "tropical"],
    width: 960,
    height: 1280,
    source: "gil-2026-07",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-006",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546990/canarycove-album2021-006.jpg",
    alt: "Spa-quality bathroom with angular mirror wall, dual vanities, and pristine white marble.",
    category: "suites-bedrooms",
    tags: ["bathroom", "spa-style", "dual-vanity", "luxury"],
    width: 2400,
    height: 3200,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-033",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546996/canarycove-album2021-033.jpg",
    alt: "Spa-inspired walk-in shower with glass enclosure and blue mosaic tile accents.",
    category: "living-spaces",
    tags: ["bathroom", "shower", "spa-inspired", "luxury"],
    width: 2400,
    height: 3200,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-009",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546991/canarycove-album2021-009.jpg",
    alt: "Resort-style pool compound with spa, colorful float collection, and palm-fringed waterfront.",
    category: "pool",
    tags: ["pool", "spa", "resort", "oceanview"],
    width: 2400,
    height: 1800,
    source: "album-2021",
    usedIn: [],
    amenities: ["pool"],
  },
  {
    id: "canarycove-album2021-059",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547003/canarycove-album2021-059.jpg",
    alt: "Villa compound vista with landscaped lawn, pink main residence, and palm-lined gardens.",
    category: "villa-exterior",
    tags: ["exterior view", "manicured grounds", "villa grounds", "palms"],
    width: 2400,
    height: 1603,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "dinnerAlt",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059647/IMG_3844-1-e1506955634238_tfro2f.webp",
    alt: "Another plated dinner presentation",
    category: "dining-food",
    tags: ["plated dinner", "presentation"],
    width: 1334,
    height: 750,
    source: "site",
    usedIn: ["app/dining/page.tsx"],
  },
  {
    id: "waterSlide",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059673/IMG_2080_stdy3b.webp",
    alt: "Guest launching from the water slide into the sea",
    category: "experiences-water",
    tags: ["water slide", "swimming", "fun"],
    width: 5184,
    height: 3456,
    source: "site",
    usedIn: ["app/experiences/page.tsx", "components/stay-outdoor-gallery.tsx"],
  },
  {
    id: "canarycove-gil2026-f564a0a1",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546988/canarycove-gil2026-f564a0a1.jpg",
    alt: "Traditional island cooking: chef prepares premium meats over crackling open flame under palms",
    category: "experiences-land",
    tags: ["outdoor-cooking", "open-fire", "culinary-experience", "tropical", "marvin", "chef marvin"],
    width: 960,
    height: 1280,
    source: "gil-2026-07",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-011",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546991/canarycove-album2021-011.jpg",
    alt: "Corner-shower master bath with dual vanities, sky-lit ceiling, and spa ambiance.",
    category: "suites-bedrooms",
    tags: ["bathroom", "corner-shower", "master-bath", "spa"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-034",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546997/canarycove-album2021-034.jpg",
    alt: "Well-appointed guest bathroom with dark wood vanity and contemporary fixtures.",
    category: "living-spaces",
    tags: ["bathroom", "vanity", "fixtures", "guest bath"],
    width: 2400,
    height: 3200,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-019",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546993/canarycove-album2021-019.jpg",
    alt: "Vibrant resort pool area with spa jets, colorful pool floats, and pink umbrellas dotting the deck.",
    category: "pool",
    tags: ["pool", "spa", "resort-style", "recreation"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
    amenities: ["pool"],
  },
  {
    id: "canarycove-album2021-102",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547013/canarycove-album2021-102.jpg",
    alt: "Terrace with sweeping curved steps, pink villa façade, colorful umbrellas, and Belize ocean backdrop.",
    category: "villa-exterior",
    tags: ["exterior", "terrace", "architecture", "ocean views"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "dinnerPlated",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059667/fa418c8c-3d8c-49bc-bdea-7f5d272d217c_u5itmk.webp",
    alt: "Plated dinner ready to serve",
    category: "dining-food",
    tags: ["plated dinner", "entree"],
    width: 960,
    height: 1280,
    source: "site",
    usedIn: ["app/dining/page.tsx"],
  },
  {
    id: "canarycove-album2021-012",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546991/canarycove-album2021-012.jpg",
    alt: "Luxe guest bedroom with jewel-toned botanical coverlet and geometric wooden headboard.",
    category: "suites-bedrooms",
    tags: ["guest-bedroom", "bedding", "headboard", "comfort"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-037",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546997/canarycove-album2021-037.jpg",
    alt: "Spa-caliber dual vanity bathroom with floor-to-ceiling mirrors and designer lighting.",
    category: "living-spaces",
    tags: ["bathroom", "dual vanity", "mirrors", "luxury"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-020",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546994/canarycove-album2021-020.jpg",
    alt: "Lush oceanfront pool setting with tropical landscaping and lounging in pure paradise.",
    category: "pool",
    tags: ["oceanfront-pool", "tropical-landscape", "lounging", "serenity"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
    amenities: ["pool"],
  },
  {
    id: "canarycove-album2021-124",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547018/canarycove-album2021-124.png",
    alt: "Contemporary villa exterior showcasing immaculate lawns, infinity pool, and resort-caliber amenities",
    category: "villa-exterior",
    tags: ["villa", "exterior", "architecture", "poolside"],
    width: 1496,
    height: 958,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "drinksBar",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059666/IMG_2393_vkftra.webp",
    alt: "Cocktails served during a San Pedro dining outing",
    category: "dining-food",
    tags: ["cocktails", "san pedro", "dining out"],
    width: 1331,
    height: 750,
    source: "site",
    usedIn: ["app/dining/page.tsx", "app/experiences/page.tsx", "components/photo-carousel.tsx"],
  },
  {
    id: "canarycove-album2021-013",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546992/canarycove-album2021-013.jpg",
    alt: "Full master bath with expansive counter space, dual sinks, and gleaming white finishes.",
    category: "suites-bedrooms",
    tags: ["bathroom", "master-bath", "spa", "luxury"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-039",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546998/canarycove-album2021-039.jpg",
    alt: "Efficient kitchenette with stainless steel appliances and convenient island counter workspace.",
    category: "living-spaces",
    tags: ["kitchen", "kitchenette", "appliances", "functional"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-031",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546996/canarycove-album2021-031.jpg",
    alt: "Resort-style infinity pool with colorful umbrellas and palm-shaded lounging area.",
    category: "pool",
    tags: ["pool", "lounge area", "tropical setting", "turquoise water"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
    amenities: ["infinity-edge"],
  },
  {
    id: "canarycove-album2021-127",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547019/canarycove-album2021-127.png",
    alt: "Villa forecourt with sweeping tiered architecture, yellow umbrellas, and professional landscaping",
    category: "villa-exterior",
    tags: ["villa-exterior", "architecture", "outdoor-entertaining", "design"],
    width: 1494,
    height: 992,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "heroBackgroundBar",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059679/63_bar_cropped-1_ujmiwg.webp",
    alt: "Outdoor bar and grill terrace overlooking the water",
    category: "dining-food",
    tags: ["bar", "grill", "terrace", "outdoor dining"],
    width: 800,
    height: 500,
    source: "site",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-015",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546992/canarycove-album2021-015.jpg",
    alt: "Pristine en-suite bathroom with statement mirror wall and spa-quality fixtures.",
    category: "suites-bedrooms",
    tags: ["bathroom", "en-suite", "mirror-wall", "luxury"],
    width: 2400,
    height: 1603,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-040",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546998/canarycove-album2021-040.jpg",
    alt: "Grand chef's kitchen with center island, premium appliances, and seamless living area flow.",
    category: "living-spaces",
    tags: ["chef's kitchen", "island", "open concept", "luxury appliances"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-038",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546998/canarycove-album2021-038.jpg",
    alt: "Tropical paradise pool deck with candy-colored umbrellas and crystal-clear turquoise water.",
    category: "pool",
    tags: ["pool", "tropical", "umbrellas", "palm trees"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
    amenities: ["pool"],
  },
  {
    id: "logoDrink",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059679/IMG_1198_d9bmki.webp",
    alt: "Canary Cove cocktail in focus with guests relaxing by the pool",
    category: "dining-food",
    tags: ["cocktail", "drinks", "branding", "poolside", "guests"],
    width: 5472,
    height: 3648,
    source: "site",
    usedIn: ["app/dining/page.tsx", "components/stay-highlights.tsx"],
  },
  {
    id: "canarycove-album2021-016",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546992/canarycove-album2021-016.jpg",
    alt: "Bright powder room bath with minimalist design and coastal aesthetic details.",
    category: "suites-bedrooms",
    tags: ["bathroom", "vanity", "coastal-style", "compact"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-041",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546998/canarycove-album2021-041.jpg",
    alt: "Refined guest bathroom with sculptural wood-framed mirror and artisan lighting fixtures.",
    category: "living-spaces",
    tags: ["bathroom", "powder room", "mirror design", "vanity"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-045",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546999/canarycove-album2021-045.jpg",
    alt: "Intimate resort pool with integrated spa feature and direct beach access through palms.",
    category: "pool",
    tags: ["pool", "spa", "beach access", "tropical"],
    width: 2400,
    height: 3200,
    source: "album-2021",
    usedIn: [],
    amenities: ["pool"],
  },
  {
    id: "saladAlt",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059653/IMG_3824-1_kchxn6.webp",
    alt: "Fresh salad served at Canary Cove",
    category: "dining-food",
    tags: ["salad", "fresh", "starter"],
    width: 720,
    height: 960,
    source: "site",
    usedIn: ["app/dining/page.tsx"],
  },
  {
    id: "canarycove-album2021-018",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546993/canarycove-album2021-018.jpg",
    alt: "Tranquil guest suite bedroom with direct patio access and serene botanical linens.",
    category: "suites-bedrooms",
    tags: ["guest-suite", "patio-access", "bedroom", "ocean-view"],
    width: 2400,
    height: 1603,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-044",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546999/canarycove-album2021-044.jpg",
    alt: "Contemporary dual-sink master bathroom with expansive mirrored wall and integrated lighting.",
    category: "living-spaces",
    tags: ["bathroom", "dual sink", "mirrors", "modern design"],
    width: 2400,
    height: 3595,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-047",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547000/canarycove-album2021-047.jpg",
    alt: "Show-stopping resort pool with columned pavilion, azure waters, and unobstructed ocean horizon.",
    category: "pool",
    tags: ["pool", "gazebo", "pavilion", "ocean view"],
    width: 2400,
    height: 1800,
    source: "album-2021",
    usedIn: [],
    amenities: ["pool"],
  },
  {
    id: "shrimpDinner",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059672/Shrimp-Dinner_s3xcug.webp",
    alt: "Shrimp dinner plated",
    category: "dining-food",
    tags: ["shrimp", "seafood", "dinner", "plated"],
    width: 2048,
    height: 1536,
    source: "site",
    usedIn: ["app/dining/page.tsx"],
  },
  {
    id: "canarycove-album2021-021",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546994/canarycove-album2021-021.jpg",
    alt: "Contemporary guest bedroom with entertainment center and direct garden access.",
    category: "suites-bedrooms",
    tags: ["guest-bedroom", "tv-room", "modern", "bedroom"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-049",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547000/canarycove-album2021-049.jpg",
    alt: "Light-filled kitchen nook with plantation shutters framing lush tropical landscape vistas.",
    category: "living-spaces",
    tags: ["kitchen", "plantation shutters", "ocean view", "tropical"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-048",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547000/canarycove-album2021-048.jpg",
    alt: "Serene pool terrace framed by swaying palms, vibrant lounge umbrellas, and turquoise water.",
    category: "pool",
    tags: ["pool", "terrace", "palms", "turquoise"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
    amenities: ["pool"],
  },
  {
    id: "tacosAlt",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1761059634/IMG_3841-1_vkm26b.webp",
    alt: "Taco spread ready to serve",
    category: "dining-food",
    tags: ["tacos", "spread", "casual"],
    width: 1334,
    height: 750,
    source: "site",
    usedIn: ["app/dining/page.tsx"],
  },
  {
    id: "canarycove-album2021-023",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546994/canarycove-album2021-023.jpg",
    alt: "Spa-inspired bathroom with dual vanities, blue tile band, and designer mirror.",
    category: "suites-bedrooms",
    tags: ["bathroom", "spa-style", "dual-vanity", "tile-accents"],
    width: 2400,
    height: 1603,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-050",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547000/canarycove-album2021-050.jpg",
    alt: "Sophisticated chef's kitchen with designer cabinetry, ocean vistas, and premium appliances.",
    category: "living-spaces",
    tags: ["chef's kitchen", "cabinetry", "ocean view", "stainless steel"],
    width: 2400,
    height: 1603,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-058",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547003/canarycove-album2021-058.jpg",
    alt: "Crystal-clear turquoise pool with pink villa building, lounge seating, and thatch-roof pergola.",
    category: "pool",
    tags: ["swimming pool", "clear water", "poolside cabana", "umbrellas"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
    amenities: ["pool"],
  },
  {
    id: "canarycove-gil2026-04e30881",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546985/canarycove-gil2026-04e30881.jpg",
    alt: "Exquisitely plated ceviche and seafood medley with lime, mango, and vibrant garnishes on slate",
    category: "dining-food",
    tags: ["ceviche", "seafood", "fine-dining", "plating"],
    width: 960,
    height: 1280,
    source: "gil-2026-07",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-024",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546994/canarycove-album2021-024.jpg",
    alt: "Comfortable bedroom retreat with glass-door patio access and modern wood detailing.",
    category: "suites-bedrooms",
    tags: ["bedroom", "patio-access", "guest-room", "modern"],
    width: 2400,
    height: 3596,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-051",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547001/canarycove-album2021-051.jpg",
    alt: "Modern kitchen workspace with mixed wood tones, expansive counter surfaces, and ocean vistas.",
    category: "living-spaces",
    tags: ["kitchen", "countertops", "mixed wood", "ocean view"],
    width: 2400,
    height: 1800,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-060",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547003/canarycove-album2021-060.jpg",
    alt: "Poolside gazebo with thatched roof framing turquoise water and distant ocean horizon.",
    category: "pool",
    tags: ["gazebo structure", "pool deck", "ocean view", "tropical design"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
    amenities: ["pool"],
  },
  {
    id: "canarycove-gil2026-2d0b8df1",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546985/canarycove-gil2026-2d0b8df1.jpg",
    alt: "Mixologist crafting champagne cocktails with precision and artistry",
    category: "dining-food",
    tags: ["cocktails", "mixology", "champagne", "beverages"],
    width: 960,
    height: 1280,
    source: "gil-2026-07",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-026",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546995/canarycove-album2021-026.jpg",
    alt: "Luxurious oceanfront master bedroom with woven seating nook and private veranda.",
    category: "suites-bedrooms",
    tags: ["master-bedroom", "oceanfront", "veranda", "luxury-suite"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-054",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547001/canarycove-album2021-054.jpg",
    alt: "Spa-like master bathroom with extensive vanity counter, tile detailing, and artistic mirrors.",
    category: "living-spaces",
    tags: ["bathroom", "master bath", "vanity", "spa"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-062",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547003/canarycove-album2021-062.jpg",
    alt: "Main pool and spa area with floating lounges, vibrant umbrellas, and oceanfront views.",
    category: "pool",
    tags: ["swimming pool", "spa area", "colorful umbrellas", "ocean backdrop"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
    amenities: ["pool"],
  },
  {
    id: "canarycove-gil2026-3f001159",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546985/canarycove-gil2026-3f001159.jpg",
    alt: "Showstopping passion-fruit cheesecake with silky cream and pistachio garnish",
    category: "dining-food",
    tags: ["dessert", "cheesecake", "gourmet", "pastry"],
    width: 960,
    height: 1280,
    source: "gil-2026-07",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-028",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546995/canarycove-album2021-028.jpg",
    alt: "Serene suite bedroom with glass doors opening directly to a furnished oceanside terrace.",
    category: "suites-bedrooms",
    tags: ["bedroom", "ocean-view", "terrace-access", "luxury-suite"],
    width: 2400,
    height: 1603,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-055",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547001/canarycove-album2021-055.jpg",
    alt: "Expansive great room with soaring ceilings, sculptural palm fans, and seamless kitchen integration.",
    category: "living-spaces",
    tags: ["living room", "great room", "open concept", "ceiling design"],
    width: 2400,
    height: 1800,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-066",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547004/canarycove-album2021-066.jpg",
    alt: "Resort-style pool area with floating lounges, cabana structure, and ocean horizon.",
    category: "pool",
    tags: ["pool lounging", "vacation setting", "tropical cabana", "oceanfront"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
    amenities: ["pool"],
  },
  {
    id: "canarycove-gil2026-53651821",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546985/canarycove-gil2026-53651821.jpg",
    alt: "Delicate raspberry tartlets with rose-tinted frosting displayed on refined porcelain",
    category: "dining-food",
    tags: ["pastry", "tartlets", "dessert", "elegant"],
    width: 960,
    height: 1280,
    source: "gil-2026-07",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-029",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546995/canarycove-album2021-029.jpg",
    alt: "Elegantly appointed guest bedroom with entertainment system and tropical-inspired decor.",
    category: "suites-bedrooms",
    tags: ["bedroom", "entertainment", "guest suite", "tropical"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-056",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547002/canarycove-album2021-056.jpg",
    alt: "Grand living pavilion with architectural ceiling fans and expansive seating toward ocean views.",
    category: "living-spaces",
    tags: ["living room", "seating area", "ceiling fans", "open concept"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-067",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547004/canarycove-album2021-067.jpg",
    alt: "Lap pool with lane markers amid lush palmery and secondary spa features.",
    category: "pool",
    tags: ["lap pool", "swimming lanes", "landscaping", "fitness pool"],
    width: 2400,
    height: 1800,
    source: "album-2021",
    usedIn: [],
    amenities: ["pool"],
  },
  {
    id: "canarycove-gil2026-649f5ea2",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546985/canarycove-gil2026-649f5ea2.jpg",
    alt: "Succulent crab and seafood tower arrayed on glass with citrus and herbs",
    category: "dining-food",
    tags: ["crab", "seafood", "appetizer", "presentation"],
    width: 960,
    height: 1280,
    source: "gil-2026-07",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-030",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546995/canarycove-album2021-030.jpg",
    alt: "Luxurious master suite with nautical sailing art and woven palm-blade ceiling fan.",
    category: "suites-bedrooms",
    tags: ["master bedroom", "sailing art", "luxury decor", "ocean view"],
    width: 2400,
    height: 1603,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-063",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547004/canarycove-album2021-063.jpg",
    alt: "Spa-inspired bathroom with dual vanities, blue tile accents, and marble finishes.",
    category: "living-spaces",
    tags: ["bathroom", "dual vanity", "luxury fixtures", "marble countertop"],
    width: 2400,
    height: 1603,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-069",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547005/canarycove-album2021-069.jpg",
    alt: "Ornate circular hot tub with intricate blue mosaic tilework and integrated spa design.",
    category: "pool",
    tags: ["spa tub", "mosaic tile", "hot tub", "luxury amenities"],
    width: 2400,
    height: 3200,
    source: "album-2021",
    usedIn: [],
    amenities: ["hot-tub"],
  },
  {
    id: "canarycove-gil2026-6dd283a9",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546986/canarycove-gil2026-6dd283a9.jpg",
    alt: "Tropical celebration with fresh pineapple and champagne cocktails garnished with mint",
    category: "dining-food",
    tags: ["tropical", "cocktails", "pineapple", "celebration"],
    width: 960,
    height: 1280,
    source: "gil-2026-07",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-035",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546996/canarycove-album2021-035.jpg",
    alt: "Inviting guest bedroom with vibrant coral-patterned linens and decorative accent pillows.",
    category: "suites-bedrooms",
    tags: ["guest bedroom", "coral patterns", "colorful decor", "cozy"],
    width: 958,
    height: 1280,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-064",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547004/canarycove-album2021-064.jpg",
    alt: "Walk-in shower enclosure with glass doors, blue tile detailing, and spa-quality design.",
    category: "living-spaces",
    tags: ["shower", "glass enclosure", "blue tile", "luxury bath"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-076",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547007/canarycove-album2021-076.jpg",
    alt: "Architectural hot tub with striking blue mosaic tilework overlooking resort grounds.",
    category: "pool",
    tags: ["spa feature", "decorative tiling", "hot tub", "artistic design"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
    amenities: ["hot-tub"],
  },
  {
    id: "canarycove-gil2026-7c1399ca",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546986/canarycove-gil2026-7c1399ca.jpg",
    alt: "Abundant fruit and artisanal cheese board bursting with mango, kiwi, berries, and fresh cheese",
    category: "dining-food",
    tags: ["charcuterie", "cheese", "fruit", "appetizer"],
    width: 960,
    height: 1280,
    source: "gil-2026-07",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-036",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546997/canarycove-album2021-036.jpg",
    alt: "Serene oceanfront master bedroom with woven palm ceiling fan and blue botanical bedding.",
    category: "suites-bedrooms",
    tags: ["master bedroom", "oceanfront", "tropical design", "palm fan"],
    width: 2400,
    height: 3200,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-065",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547004/canarycove-album2021-065.jpg",
    alt: "Open-concept living room with cream seating, wicker accents, and soaring wood ceilings.",
    category: "living-spaces",
    tags: ["living room", "modern seating", "high ceilings", "wicker furniture"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-085",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547008/canarycove-album2021-085.jpg",
    alt: "Crystalline infinity pool with thatched-roof palapa, crocodile statue, and palm-lined ocean views at sunset.",
    category: "pool",
    tags: ["infinity pool", "ocean view", "tropical", "luxury resort"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
    amenities: ["infinity-edge"],
  },
  {
    id: "canarycove-gil2026-8cb0308b",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546986/canarycove-gil2026-8cb0308b.jpg",
    alt: "Grilled fish, premium shrimp, and fresh mussels arranged on dark slate with lime and herbs",
    category: "dining-food",
    tags: ["seafood", "grilled", "presentation", "fine-dining"],
    width: 960,
    height: 1280,
    source: "gil-2026-07",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-042",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546998/canarycove-album2021-042.jpg",
    alt: "Charming guest suite with coral botanical bedding and playful patterned accent pillows.",
    category: "suites-bedrooms",
    tags: ["guest bedroom", "coral patterns", "colorful", "cozy"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-068",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547004/canarycove-album2021-068.jpg",
    alt: "Furnished patio terrace with lounge seating under yellow umbrella and ocean vistas.",
    category: "living-spaces",
    tags: ["patio", "outdoor seating", "sun shelter", "ocean view"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-111",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547015/canarycove-album2021-111.jpg",
    alt: "Crystalline lap pool extending toward turquoise Caribbean waters with private beach and palm canopy.",
    category: "pool",
    tags: ["swimming pool", "beach access", "ocean view", "private"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
    amenities: ["pool"],
  },
  {
    id: "canarycove-gil2026-97921790",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546987/canarycove-gil2026-97921790.jpg",
    alt: "Tropical mocktails and champagne cocktails with pineapple charred garnish and fresh mint",
    category: "dining-food",
    tags: ["tropical", "cocktails", "beverages", "presentation"],
    width: 960,
    height: 1280,
    source: "gil-2026-07",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-043",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546999/canarycove-album2021-043.jpg",
    alt: "Sophisticated oceanfront master bedroom with resort-style amenities and water views.",
    category: "suites-bedrooms",
    tags: ["master bedroom", "oceanfront", "sliding doors", "ocean view"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-072",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547006/canarycove-album2021-072.png",
    alt: "Luxurious dual-vanity master bathroom with blue tile accents and marble surfaces.",
    category: "living-spaces",
    tags: ["master bath", "dual sink", "marble", "tile work"],
    width: 1496,
    height: 974,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-112",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547015/canarycove-album2021-112.jpg",
    alt: "Resort-style pool deck with colorful lounges, crocodile statue, palms, and pristine turquoise waters.",
    category: "pool",
    tags: ["pool lounge", "beach resort", "tropical", "leisure"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
    amenities: ["pool"],
  },
  {
    id: "canarycove-gil2026-cea38c0a",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546987/canarycove-gil2026-cea38c0a.jpg",
    alt: "Fresh-cracked crab and chilled seafood selection garnished with lime on clear glass plate",
    category: "dining-food",
    tags: ["crab", "seafood", "fresh", "appetizer"],
    width: 960,
    height: 1280,
    source: "gil-2026-07",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-052",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547001/canarycove-album2021-052.jpg",
    alt: "Oceanview suite bedroom with tropical woven ceiling fan and direct pool deck access.",
    category: "suites-bedrooms",
    tags: ["bedroom", "pool view", "sliding doors", "tropical fan"],
    width: 2400,
    height: 1800,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-073",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547006/canarycove-album2021-073.jpg",
    alt: "Spa-style bathroom with glass-enclosed shower and crisp blue-and-white tile design.",
    category: "living-spaces",
    tags: ["bathroom", "shower enclosure", "blue tile", "spa amenities"],
    width: 2400,
    height: 1800,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-114",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547016/canarycove-album2021-114.png",
    alt: "Inviting pool deck with shaded lounge chairs and unobstructed ocean backdrop lined with tropical palms",
    category: "pool",
    tags: ["pool", "lounging", "oceanfront", "umbrellas"],
    width: 1496,
    height: 978,
    source: "album-2021",
    usedIn: [],
    amenities: ["pool"],
  },
  {
    id: "canarycove-gil2026-e8782492",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546987/canarycove-gil2026-e8782492.jpg",
    alt: "Silky passion-fruit cheesecake with dark chocolate ganache and creamy topping",
    category: "dining-food",
    tags: ["dessert", "cheesecake", "gourmet", "chocolate"],
    width: 960,
    height: 1280,
    source: "gil-2026-07",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-053",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547001/canarycove-album2021-053.jpg",
    alt: "Charming guest bedroom with botanical-print bedding and classic dark wood furnishings.",
    category: "suites-bedrooms",
    tags: ["guest bedroom", "botanical patterns", "wood headboard", "cozy"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-082",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547008/canarycove-album2021-082.jpg",
    alt: "Bright interior hallway with modern design and refined lighting fixtures.",
    category: "living-spaces",
    tags: ["corridor", "interior design", "lighting", "modern aesthetic"],
    width: 2400,
    height: 1800,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-116",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547016/canarycove-album2021-116.jpg",
    alt: "Resort-style infinity pool framed by colorful umbrellas, palm trees, and a waterfront tiki bar",
    category: "pool",
    tags: ["infinity-pool", "resort-style", "oceanfront", "tropical"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
    amenities: ["infinity-edge", "pool-bar"],
  },
  {
    id: "canarycove-gil2026-f9564a98",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546988/canarycove-gil2026-f9564a98.jpg",
    alt: "Jeweled cheesecake tartlets layered with chocolate ganache, berries, and mint",
    category: "dining-food",
    tags: ["dessert", "cheesecake", "berries", "gourmet"],
    width: 960,
    height: 1280,
    source: "gil-2026-07",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-061",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547003/canarycove-album2021-061.jpg",
    alt: "Master bedroom suite with king bed, coral floral linens, and rich wood furnishings.",
    category: "suites-bedrooms",
    tags: ["master suite", "king bed", "luxury linens", "dark wood"],
    width: 2400,
    height: 1800,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-087",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547009/canarycove-album2021-087.jpg",
    alt: "Sophisticated living room with cream linen sofa, woven seating, and dark wood architectural details.",
    category: "living-spaces",
    tags: ["living room", "interior design", "coastal elegance", "entertainment"],
    width: 2400,
    height: 1603,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-120",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547017/canarycove-album2021-120.jpg",
    alt: "Tranquil spa and pool area with tiki-roofed structures nestled among swaying palms and ocean views",
    category: "pool",
    tags: ["spa", "pool", "relaxation", "tropical-setting"],
    width: 2400,
    height: 1800,
    source: "album-2021",
    usedIn: [],
    amenities: ["pool"],
  },
  {
    id: "canarycove-gil2026-fa418c8c",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546988/canarycove-gil2026-fa418c8c.jpg",
    alt: "Elegant tasting journey: ceviche, grilled fish, and seafood preparations arranged on slate",
    category: "dining-food",
    tags: ["tasting-menu", "seafood", "ceviche", "presentation"],
    width: 960,
    height: 1280,
    source: "gil-2026-07",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-070",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547005/canarycove-album2021-070.jpg",
    alt: "Ocean-view guest bedroom with king bed, wicker seating, and direct patio access.",
    category: "suites-bedrooms",
    tags: ["guest room", "oceanfront", "king bed", "patio doors"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-094",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547011/canarycove-album2021-094.jpg",
    alt: "Suite entertainment nook with wall-mounted television and custom dark wood media cabinetry.",
    category: "living-spaces",
    tags: ["entertainment", "media room", "custom cabinetry", "modern"],
    width: 2400,
    height: 1800,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-121",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547018/canarycove-album2021-121.jpg",
    alt: "Scenic pool deck featuring shaded lounging pavilion with authentic Belizean wooden sculpture accents",
    category: "pool",
    tags: ["pool", "lounging", "oceanfront", "art-decor"],
    width: 2400,
    height: 1603,
    source: "album-2021",
    usedIn: [],
    amenities: ["pool"],
  },
  {
    id: "canarycove-album2021-022",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546994/canarycove-album2021-022.jpg",
    alt: "Elegant round dining table with sea-view backdrop, sculptural ceiling, and resort ambiance.",
    category: "dining-food",
    tags: ["dining-room", "ocean-view", "round-table", "formal-dining"],
    width: 2400,
    height: 1603,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-071",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547005/canarycove-album2021-071.jpg",
    alt: "Guest bedroom with dark wood furnishings, blue-white bedding, and tropical décor.",
    category: "suites-bedrooms",
    tags: ["guest suite", "coastal style", "traditional wood", "botanical linens"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-103",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547013/canarycove-album2021-103.jpg",
    alt: "Open-concept living, kitchen, and dining area with wood-slat ceiling and seamless indoor-outdoor flow.",
    category: "living-spaces",
    tags: ["open plan", "kitchen", "dining", "luxury living"],
    width: 2400,
    height: 1603,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-125",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547018/canarycove-album2021-125.jpg",
    alt: "Serene poolside retreat with shaded pavilion, ready loungers, and pristine ocean backdrop",
    category: "pool",
    tags: ["pool", "lounging", "oceanfront", "relaxation"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
    amenities: ["pool"],
  },
  {
    id: "canarycove-album2021-027",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785546995/canarycove-album2021-027.jpg",
    alt: "Gourmet open kitchen flowing into dining and lounge spaces with seamless ocean sightlines.",
    category: "dining-food",
    tags: ["open-kitchen", "dining", "ocean-view", "culinary"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-075",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547006/canarycove-album2021-075.jpg",
    alt: "Guest suite bedroom with queen bed, blue botanical linens, and patio ocean access.",
    category: "suites-bedrooms",
    tags: ["guest bedroom", "queen bed", "patio access", "island style"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-110",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547015/canarycove-album2021-110.jpg",
    alt: "Grand living space with full-height glass doors opening to pool deck and infinite ocean views.",
    category: "living-spaces",
    tags: ["living room", "glass doors", "pool view", "luxury"],
    width: 2400,
    height: 1800,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-101",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547013/canarycove-album2021-101.jpg",
    alt: "Chef's kitchen opening to dining and living areas with stainless steel appliances and island bar.",
    category: "dining-food",
    tags: ["kitchen", "dining", "chef's kitchen", "modern appliances"],
    width: 2400,
    height: 1603,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-077",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547007/canarycove-album2021-077.jpg",
    alt: "Bedroom with ocean patio, king bed, botanical bedding, and direct water views.",
    category: "suites-bedrooms",
    tags: ["oceanfront bedroom", "king bed", "sliding doors", "water view"],
    width: 2400,
    height: 1800,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-113",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547016/canarycove-album2021-113.jpg",
    alt: "Spacious open-concept living room with sectional seating and oceanfront views through expansive glass doors",
    category: "living-spaces",
    tags: ["living-room", "oceanview", "modern", "seating"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-108",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547014/canarycove-album2021-108.jpg",
    alt: "Professional kitchen with stainless steel range, island counter, and access to palm-tree gardens.",
    category: "dining-food",
    tags: ["kitchen", "cooking", "gourmet", "stainless steel"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-080",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547007/canarycove-album2021-080.jpg",
    alt: "Master suite with king bed, rattan ceiling fan, and expansive ocean-view sliding doors.",
    category: "suites-bedrooms",
    tags: ["master bedroom", "oceanfront", "water view", "king bed"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-118",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547017/canarycove-album2021-118.jpg",
    alt: "Bright open-concept living space with cream furnishings and seamless indoor-outdoor flow to pool and ocean",
    category: "living-spaces",
    tags: ["living-room", "oceanview", "openplan", "contemporary"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-123",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547017/canarycove-album2021-123.jpg",
    alt: "Elegant open-plan dining and living space unified by dramatic wood-vaulted ceiling and ocean views",
    category: "dining-food",
    tags: ["dining", "openplan", "architecture", "oceanfront"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-081",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547008/canarycove-album2021-081.jpg",
    alt: "Elegant guest bedroom with botanical blue linens and refined dark wood bed frame.",
    category: "suites-bedrooms",
    tags: ["guest room", "tropical decor", "dark wood", "coastal style"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-122",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547017/canarycove-album2021-122.jpg",
    alt: "Sophisticated great room with soaring wood-slatted ceiling, entertainment center, and commanding ocean vistas",
    category: "living-spaces",
    tags: ["great-room", "entertainment", "oceanview", "architectural"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-130",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547019/canarycove-album2021-130.jpg",
    alt: "Chef's kitchen adjoining great room with gourmet island cooktop and seamless pool-and-ocean sightlines",
    category: "dining-food",
    tags: ["kitchen", "gourmet", "cooking-island", "oceanview"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-083",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547008/canarycove-album2021-083.jpg",
    alt: "Guest bedroom with king bed, blue-white botanical linens, and island furnishings.",
    category: "suites-bedrooms",
    tags: ["guest suite", "king bed", "coastal decor", "botanical prints"],
    width: 2400,
    height: 1603,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-132",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547020/canarycove-album2021-132.jpg",
    alt: "Intimate formal dining room with round table, ocean vistas, and distinctive sun-motif wall sculpture",
    category: "dining-food",
    tags: ["formal-dining", "oceanview", "luxury", "art-decor"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-084",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547009/canarycove-album2021-084.jpg",
    alt: "Master oceanfront suite with panoramic sliding glass doors and tropical ceiling design.",
    category: "suites-bedrooms",
    tags: ["master suite", "oceanfront", "luxury bedroom", "water views"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-133",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547020/canarycove-album2021-133.jpg",
    alt: "Gourmet chef's kitchen featuring premium stainless steel appliances, island bar, and wood-vaulted ceiling",
    category: "dining-food",
    tags: ["kitchen", "gourmet", "cooking-island", "professional"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-086",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547009/canarycove-album2021-086.jpg",
    alt: "Spa-inspired master bathroom featuring dual vanities with blue tile accents and spa shower.",
    category: "suites-bedrooms",
    tags: ["bathroom", "spa", "dual vanity", "luxury"],
    width: 2400,
    height: 1800,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-135",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547020/canarycove-album2021-135.jpg",
    alt: "Fully-appointed secondary kitchen with wood-framed windows, gray tile backsplash, and professional finishes",
    category: "dining-food",
    tags: ["secondary-kitchen", "gourmet", "modern", "entertaining"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-088",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547010/canarycove-album2021-088.jpg",
    alt: "Light-filled master bedroom with hand-crafted dark wood bed and terrace overlooking tropical gardens.",
    category: "suites-bedrooms",
    tags: ["master bedroom", "ocean access", "wood furniture", "daylight"],
    width: 2400,
    height: 1800,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-136",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547021/canarycove-album2021-136.jpg",
    alt: "Elegant formal dining room with round table, tropical artwork, and integrated kitchen overlooking the estate",
    category: "dining-food",
    tags: ["formal-dining", "tropical-art", "oceanview", "luxury"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-089",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547010/canarycove-album2021-089.jpg",
    alt: "Master suite bedroom with blue botanical-patterned bedding and direct access to garden terrace.",
    category: "suites-bedrooms",
    tags: ["master suite", "terrace access", "coastal style", "comfortable"],
    width: 2400,
    height: 3200,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-090",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547010/canarycove-album2021-090.jpg",
    alt: "Dual-sink master bathroom with turquoise tile accents and brightly lit mirror walls.",
    category: "suites-bedrooms",
    tags: ["bathroom", "tile work", "dual sink", "spa-like"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-091",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547010/canarycove-album2021-091.jpg",
    alt: "Bedroom with custom geometric wood headboard, blue patterned linens, and palm-tree ocean views.",
    category: "suites-bedrooms",
    tags: ["bedroom", "ocean view", "luxury linens", "custom furniture"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-092",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547010/canarycove-album2021-092.jpg",
    alt: "Guest bedroom with woven wood headboard, blue coastal bedding, and serene tropical setting.",
    category: "suites-bedrooms",
    tags: ["bedroom", "nautical", "relaxing", "woven details"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-093",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547011/canarycove-album2021-093.jpg",
    alt: "Children's bunk bedroom with blue bedding featuring decorative shell and hibiscus accents.",
    category: "suites-bedrooms",
    tags: ["children's room", "bunk beds", "family-friendly", "tropical"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
    suite: "bunk-room",
  },
  {
    id: "canarycove-album2021-095",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547011/canarycove-album2021-095.jpg",
    alt: "Luxurious master bedroom featuring dramatic wood ceiling, floral bedding, and oceanside terrace.",
    category: "suites-bedrooms",
    tags: ["master bedroom", "wood ceiling", "terrace", "upscale"],
    width: 2400,
    height: 1603,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-096",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547011/canarycove-album2021-096.jpg",
    alt: "Master suite with sculptural ceiling fan, wood beams overhead, and private oceanview balcony.",
    category: "suites-bedrooms",
    tags: ["master suite", "ceiling fan", "architectural", "ocean access"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-097",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547011/canarycove-album2021-097.jpg",
    alt: "Guest bedroom with entertainment console, flat-screen TV, and tropical coastal décor.",
    category: "suites-bedrooms",
    tags: ["guest room", "TV", "coastal décor", "comfortable"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-098",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547011/canarycove-album2021-098.jpg",
    alt: "Bedroom suite featuring contemporary wood furnishings and soft blue-patterned linens.",
    category: "suites-bedrooms",
    tags: ["bedroom", "modern furnishings", "relaxed", "coastal"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-099",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547012/canarycove-album2021-099.jpg",
    alt: "Bedroom with bold coral-floral bedding, dark wood frame, and window views of palm trees.",
    category: "suites-bedrooms",
    tags: ["bedroom", "floral", "vibrant", "tropical"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-100",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547012/canarycove-album2021-100.jpg",
    alt: "Expansive master bedroom with dramatic wooden beams, king bed, and dramatic ocean-view doors.",
    category: "suites-bedrooms",
    tags: ["master bedroom", "open space", "architectural", "luxury"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-104",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547013/canarycove-album2021-104.jpg",
    alt: "Spa bathroom with expansive mirror wall, blue tile border, and vanity lighting.",
    category: "suites-bedrooms",
    tags: ["bathroom", "spa", "mirror", "tile detail"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-105",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547013/canarycove-album2021-105.jpg",
    alt: "Master bathroom vanity corner with bright lighting and elegant finishes.",
    category: "suites-bedrooms",
    tags: ["bathroom", "vanity", "lighting", "luxury"],
    width: 2400,
    height: 1603,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-106",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547014/canarycove-album2021-106.jpg",
    alt: "Master bathroom featuring wide vanity with turquoise tile accent stripe and contemporary lighting.",
    category: "suites-bedrooms",
    tags: ["bathroom", "vanity", "tile work", "modern"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-107",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547014/canarycove-album2021-107.jpg",
    alt: "Walk-in shower with teal tile accents and spa-style fixtures in serene bathroom setting.",
    category: "suites-bedrooms",
    tags: ["shower", "bathroom", "teal tile", "spa"],
    width: 2400,
    height: 1603,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-109",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547015/canarycove-album2021-109.jpg",
    alt: "Guest bedroom showcasing geometric-patterned bedding with soft neutral and sea-blue tones.",
    category: "suites-bedrooms",
    tags: ["bedroom", "geometric", "pattern", "coastal"],
    width: 2400,
    height: 1800,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-115",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547016/canarycove-album2021-115.jpg",
    alt: "Luxurious master suite with glass doors opening to a private ocean-view pool and tiki shelter",
    category: "suites-bedrooms",
    tags: ["master-bedroom", "oceanview", "private-pool", "luxury"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-117",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547016/canarycove-album2021-117.jpg",
    alt: "Spa-inspired dual-vanity bathroom with gleaming blue subway tile and premium fixtures",
    category: "suites-bedrooms",
    tags: ["bathroom", "dual-vanity", "spa-style", "modern"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-119",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547017/canarycove-album2021-119.jpg",
    alt: "Contemporary guest bathroom with spacious walk-in shower and turquoise tile accents",
    category: "suites-bedrooms",
    tags: ["bathroom", "shower", "modern", "guest-suite"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-126",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547019/canarycove-album2021-126.jpg",
    alt: "Charming guest bedroom with tropical coral-print bedding, wood headboard, and ocean-view glass doors",
    category: "suites-bedrooms",
    tags: ["guest-bedroom", "tropical", "oceanview", "colorful"],
    width: 2400,
    height: 3200,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-128",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547019/canarycove-album2021-128.jpg",
    alt: "Serene master bedroom opening to panoramic pool and ocean vistas through floor-to-ceiling glass",
    category: "suites-bedrooms",
    tags: ["master-bedroom", "oceanview", "luxury", "private-pool"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-129",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547019/canarycove-album2021-129.jpg",
    alt: "Spacious spa-style bathroom featuring marble accents, generously proportioned shower, and modern finishes",
    category: "suites-bedrooms",
    tags: ["bathroom", "spa-style", "shower", "luxurious"],
    width: 2400,
    height: 1800,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-131",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547020/canarycove-album2021-131.jpg",
    alt: "Inviting guest suite with nautical-inspired bedding, sailboat artwork, and direct patio access to palms",
    category: "suites-bedrooms",
    tags: ["guest-bedroom", "nautical", "patio-access", "oceanfront"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-134",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547020/canarycove-album2021-134.jpg",
    alt: "Gracious guest bedroom opening onto private patio surrounded by mature tropical palm trees",
    category: "suites-bedrooms",
    tags: ["guest-bedroom", "patio-access", "tropical", "oceanfront"],
    width: 2400,
    height: 1602,
    source: "album-2021",
    usedIn: [],
  },
  {
    id: "canarycove-album2021-137",
    src: "https://res.cloudinary.com/dhqpqfw6w/image/upload/v1785547021/canarycove-album2021-137.jpg",
    alt: "Welcoming guest bedroom with vibrant tropical-print bedding, private en-suite bathroom, and warm natural light",
    category: "suites-bedrooms",
    tags: ["guest-bedroom", "ensuite", "tropical-decor", "comfortable"],
    width: 2400,
    height: 1800,
    source: "album-2021",
    usedIn: [],
  },
]
